// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KbeBalls {
    using KbeBalls;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using UniRx;
    using UnityEngine;
    
    
    public class LoginServiceBase : uFrame.Kernel.SystemServiceMonoBehavior {
        
        public override void Setup() {
            base.Setup();
        }
    }
    
    public class WorldViewServiceBase : uFrame.Kernel.SystemServiceMonoBehavior {
        
        public override void Setup() {
            base.Setup();
        }
    }
}
