// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KbeBalls {
    using KbeBalls;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Json;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    
    
    public partial class onDelSpaceDataEventBase : uFrame.MVVM.IJSonSerializable {
        
        private String _Key;
        
        private UInt32 _SpaceID;
        
        public String Key {
            get {
                return _Key;
            }
            set {
                _Key = value;
            }
        }
        
        public UInt32 SpaceID {
            get {
                return _SpaceID;
            }
            set {
                _SpaceID = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("Key", new JSONData(this.Key));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["Key"] != null) {
                this.Key = node["Key"].AsString;
            }
        }
    }
    
    public partial class onLeaveSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class setpositionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnLoginSuccessfullyEventBase : uFrame.MVVM.IJSonSerializable {
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class setdirectionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onEnterSpaceEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onSetSpaceDataEventBase : uFrame.MVVM.IJSonSerializable {
        
        private UInt32 _SpaceID;
        
        private String _Value;
        
        private String _Key;
        
        public UInt32 SpaceID {
            get {
                return _SpaceID;
            }
            set {
                _SpaceID = value;
            }
        }
        
        public String Value {
            get {
                return _Value;
            }
            set {
                _Value = value;
            }
        }
        
        public String Key {
            get {
                return _Key;
            }
            set {
                _Key = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("Value", new JSONData(this.Value));
            jsonObject.Add("Key", new JSONData(this.Key));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["Value"] != null) {
                this.Value = node["Value"].AsString;
            }
            if (node["Key"] != null) {
                this.Key = node["Key"].AsString;
            }
        }
    }
    
    public partial class onLeaveWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class onControlledEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        private Boolean _isControlled;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public Boolean isControlled {
            get {
                return _isControlled;
            }
            set {
                _isControlled = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("isControlled", new JSONData(this.isControlled));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["isControlled"] != null) {
                this.isControlled = node["isControlled"].AsBool;
            }
        }
    }
    
    public partial class updatePositionEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class OnAvatarEnterWorldEventBase : uFrame.MVVM.IJSonSerializable {
        
        private KBEngine.Entity _Entity;
        
        public KBEngine.Entity Entity {
            get {
                return _Entity;
            }
            set {
                _Entity = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
        }
    }
    
    public partial class addSpaceGeometryMappingEventBase : uFrame.MVVM.IJSonSerializable {
        
        private String _Respath;
        
        public String Respath {
            get {
                return _Respath;
            }
            set {
                _Respath = value;
            }
        }
        
        public virtual string Serialize() {
            var jsonObject = new JSONClass();
            jsonObject.Add("Respath", new JSONData(this.Respath));
            return jsonObject.ToString();
        }
        
        public virtual void Deserialize(string json) {
            var node = JSON.Parse(json);
            if (node["Respath"] != null) {
                this.Respath = node["Respath"].AsString;
            }
        }
    }
}
