// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KbeBalls {
    using KbeBalls;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class WorldSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        private EntityCommonController _EntityCommonController;
        
        private AvatarController _AvatarController;
        
        private SmashController _SmashController;
        
        private FoodController _FoodController;
        
        [uFrame.IOC.InjectAttribute()]
        public virtual EntityCommonController EntityCommonController {
            get {
                if (_EntityCommonController==null) {
                    _EntityCommonController = Container.CreateInstance(typeof(EntityCommonController)) as EntityCommonController;;
                }
                return _EntityCommonController;
            }
            set {
                _EntityCommonController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual AvatarController AvatarController {
            get {
                if (_AvatarController==null) {
                    _AvatarController = Container.CreateInstance(typeof(AvatarController)) as AvatarController;;
                }
                return _AvatarController;
            }
            set {
                _AvatarController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual SmashController SmashController {
            get {
                if (_SmashController==null) {
                    _SmashController = Container.CreateInstance(typeof(SmashController)) as SmashController;;
                }
                return _SmashController;
            }
            set {
                _SmashController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual FoodController FoodController {
            get {
                if (_FoodController==null) {
                    _FoodController = Container.CreateInstance(typeof(FoodController)) as FoodController;;
                }
                return _FoodController;
            }
            set {
                _FoodController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<EntityCommonViewModel>(new ViewModelManager<EntityCommonViewModel>());
            Container.RegisterController<EntityCommonController>(EntityCommonController);
            Container.RegisterViewModelManager<AvatarViewModel>(new ViewModelManager<AvatarViewModel>());
            Container.RegisterController<AvatarController>(AvatarController);
            Container.RegisterViewModelManager<SmashViewModel>(new ViewModelManager<SmashViewModel>());
            Container.RegisterController<SmashController>(SmashController);
            Container.RegisterViewModelManager<FoodViewModel>(new ViewModelManager<FoodViewModel>());
            Container.RegisterController<FoodController>(FoodController);
        }
    }
}
