/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Food : FoodBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using uFrame.IOC;
	using uFrame.Kernel;
	using uFrame.Kernel.Serialization;
	using uFrame.MVVM;
	using uFrame.MVVM.Bindings;
	using uFrame.MVVM.ViewModels;
	using UniRx;

	// defined in */scripts/entity_defs/Food.def
	public class FoodCreateCellClientCommand:uFrame.MVVM.ViewModels.ViewModelCommand{ public float arg1; public Int32 arg2; }

	// Please inherit and implement "class Food : FoodBase"
	public abstract class FoodBase : uFrame.MVVM.ViewModels.ViewModel
	{
		public EntityBaseEntityCall_FoodBase baseEntityCall = null;
		public EntityCellEntityCall_FoodBase cellEntityCall = null;


		private P<Byte> _modelIDProperty = new P<Byte>();
		public virtual P<Byte> modelIDProperty { get { return _modelIDProperty; } set { _modelIDProperty = value; } }
		public virtual Byte modelID { get { return modelIDProperty.Value; } set { modelIDProperty.Value = value; } }
		//tpublic Byte modelID = 0;
		public virtual void onModelIDChanged(Byte oldValue) {}

		public virtual void CreateCellClient(float arg1, Int32 arg2){ this.Execute(new FoodCreateCellClientCommand(){ arg1 = arg1 , arg2 = arg2 }); }
		private Signal<FoodCreateCellClientCommand> _CreateCellClientCommand;
		public virtual Signal<FoodCreateCellClientCommand> CreateCellClientCommand { get { return _CreateCellClientCommand; } set { _CreateCellClientCommand = value; } }
		public virtual void Execute(FoodCreateCellClientCommand argument) { this.CreateCellClientCommand.OnNext(argument); }

		public FoodBase(uFrame.Kernel.IEventAggregator aggregator) :base(aggregator) 
		{
			_CreateCellClientCommand = new Signal<FoodCreateCellClientCommand>(this);
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_FoodBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_FoodBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["FoodViewModel"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.useMethodDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
				methodUtype = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 13:
					float CreateCellClient_arg1 = stream.readFloat();
					Int32 CreateCellClient_arg2 = stream.readInt32();
					CreateCellClient(CreateCellClient_arg1, CreateCellClient_arg2);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["FoodViewModel"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 14:
						Byte oldval_modelID = modelID;
						modelID = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onModelIDChanged(oldval_modelID);
						}
						else
						{
							if(inWorld)
								onModelIDChanged(oldval_modelID);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["FoodViewModel"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Byte oldval_modelID = modelID;
			Property prop_modelID = pdatas[4];
			if(prop_modelID.isBase())
			{
				if(inited && !inWorld)
					onModelIDChanged(oldval_modelID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_modelID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onModelIDChanged(oldval_modelID);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
	public partial class FoodViewModel: FoodBase { public FoodViewModel(uFrame.Kernel.IEventAggregator aggregator):base(aggregator) {  } }
}