//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBEngine {
    using KBEngine;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class LoginSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "KBEngineKernelScene";
            }
        }
        
        public virtual LoginSceneSettings Settings {
            get {
                return _SettingsObject as LoginSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class WorldSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "KBEngineKernelScene";
            }
        }
        
        public virtual WorldSceneSettings Settings {
            get {
                return _SettingsObject as WorldSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
}
