// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KbeBalls {
    using KbeBalls;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class AvatarObjectViewBase : EntityCommonView {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _name;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Double _moveSpeed;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("moveSpeed")]
        [UnityEngine.HideInInspector()]
        public bool _BindmoveSpeed = true;
        
        [uFrame.MVVM.Attributes.UFGroup("moveSpeed")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_moveSpeedonlyWhenChanged")]
        protected bool _moveSpeedOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("name")]
        [UnityEngine.HideInInspector()]
        public bool _Bindname = true;
        
        [uFrame.MVVM.Attributes.UFGroup("name")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_nameonlyWhenChanged")]
        protected bool _nameOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("ReSpawn")]
        [UnityEngine.HideInInspector()]
        public bool _BindReSpawn = true;
        
        [uFrame.MVVM.Attributes.UFGroup("ReSpawn")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_ReSpawnbutton")]
        protected UnityEngine.UI.Button _ReSpawnButton;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(AvatarViewModel);
            }
        }
        
        public AvatarViewModel Avatar {
            get {
                return (AvatarViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as AvatarViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var avatarobjectview = ((AvatarViewModel)model);
            avatarobjectview.name = this._name;
            avatarobjectview.moveSpeed = this._moveSpeed;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.Avatar to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindmoveSpeed) {
                this.BindProperty(this.Avatar.moveSpeedProperty, this.moveSpeedChanged, _moveSpeedOnlyWhenChanged);
            }
            if (_Bindname) {
                this.BindProperty(this.Avatar.nameProperty, this.nameChanged, _nameOnlyWhenChanged);
            }
            if (_BindReSpawn) {
                this.BindCommandExecuted(this.Avatar.ReSpawn, this.ReSpawnExecuted);
            }
            if (_BindReSpawn) {
                this.BindButtonToCommand(_ReSpawnButton, this.Avatar.ReSpawn);
            }
        }
        
        public virtual void moveSpeedChanged(Double arg1) {
        }
        
        public virtual void nameChanged(String arg1) {
        }
        
        public virtual void ReSpawnExecuted(ReSpawnCommand command) {
        }
        
        public virtual void ExecuteReSpawn(ReSpawnCommand command) {
            command.Sender = Avatar;
            Avatar.ReSpawn.OnNext(command);
        }
    }
}
